### ISSUE TITLE
Implement `RecordsLocalDataSource` & connect `RecordsRepository` to it

### ISSUE THREAD

**Issue by nivisi** [nivisi/later#10]
In the repositories we'll need to use data sources in order to access the data.

Steps:
1. Rename `RecordModel` to `RecordDbModel` and move it under the `data/models` folder
2. Create a new class `RecordModel` with all the fields made final. Put it under `domain/models` folder.
3. Create an abstract `RecordsDataSource` with these methods:
    - `watchAll`
    - `create`
    - `getById`
4. Create an actual implementation `RecordsLocalDataSource` that make it work with `Isar` (see the logic in the current `RecordsRepository`). This local data source must be correctly annotated for `injectable`, see [the documentation](https://pub.dev/packages/injectable#binding-abstract-classes-to-implementations).
5. Make the `RecordsRepository` work with this local data source. Map `RecordDbModel`s to `RecordModel`s.

**Comment by hardioi** [comment]
@nivisi did i get clearly that i should rewrite `RecordsRepository`  class to implementing abstract class?

**Comment by nivisi** [comment]
@hardioi you can do it yep. Not required though.

**Comment by nivisi** [comment]
@hardioi jfyi, again. We're doing this to draw a dividing line between the _domain_ layer, that is related to the business logic of the app, and the _data_ layer, that is related to persistent of the data.

Why to split them?

_Data layer might change in the future. For example, we'll use another package for DB, not Isar. And this possible change must not affect domain layer in any way._

Please have another look at the `RecordModel` in its current state. It uses a lot from _isar_ and it is designed in the way only isar accepts it. And isar, in fact, has nothing to do with our app except for storing the data.

That means, we must move it to its own layer and create a way to connect it with the domain layer.

- `RecordModel` — is for _domain_ layer
- `RecordDbModel` — is for _data_ layer

It will be covered in #6, I'll explain it there.
